### ISSUE TITLE
Title Generator changes your selected title when editing a pitch

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#102]
**Describe the bug**
Title Generator changes your selected title when editing a pitch

**Steps To Reproduce**
1. Create pitch
2. Edit pitch
3. Title generator has changed your pitch measures (i.e. Desperate Measures becomes "Didn't Make the Cut")

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed!

**Comment by LemBurnstein** [comment]
Confirmed this is fixed
