### ISSUE TITLE
Edit a pitch, Post a new contribution to it, copy then open the link to the contribution, and press back arrow

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#104]
**Describe the bug**
Edit a pitch, Post a new contribution to it, copy then open the link to the contribution, and press back arrow

**Steps To Reproduce**
1. Edit a pitch, 
2. Post a new contribution to it, 
3. then copy and follow the contribution link and press back arrow
4. Taken back to old (unedited) pitch, which has any old contributions on it, but you cannot see your new contribution
5. Pressing back arrow again takes you to the updated pitch, where you can see your new contribution.
6. Refreshing the pitchboard takes you to the old pitch, cannot see new contributions.

**Expected Result**
Taken back to updated (edited) pitch, with all contributions (old and new)

Happened on both iphone and windows 10

**Comment by lovelle-cardoso** [comment]
You have to wait for the contribution to be processed by the backend before it will show up in the pitch list. It only shows up right away if you don't refresh the page or open a new tab.
