### ISSUE TITLE
Letters occasionally lost when describing a story pitch

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#107]
**Describe the bug**
When creating the description for a story pitch there is a delay between typing and the characters appearing in the dialogue box. If you type before a character has finished displaying, it will be overwritten by the next key you type.

This only happens when you type quickly (no issue when you have a second gap between letter presses)

Tried typing "For example, this is what happens when I try to type an example"

![image](https://user-images.githubusercontent.com/92612567/146124016-5edf26b7-b983-434e-9657-aa0d27b9f5a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by LemBurnstein** [comment]
Happens less now, but this is still a problem

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Should be fixed now!

**Comment by LemBurnstein** [comment]
Fixed!
