### ISSUE TITLE
Deleting image contribution to a pitch and then immediately trying to upload a new image gives permission denied error

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#108]
**Describe the bug**
Deleting image contribution to a pitch and then immediately trying to upload a new image gives permission denied error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by LemBurnstein** [comment]
This appears to be fixed

**Comment by LemBurnstein** [comment]
I seem to get this error when contributing to a pitch where there are more contributions shown then exist

Not sure if I deleted an image contribution in the past.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Can't replicate this. Can you try again?

**Comment by LemBurnstein** [comment]
Source of the issue: if an image you've uploaded gets classified as Hentai, you are still able to contribute additional image contributions

**Comment by LemBurnstein** [comment]
If your hentai post is hidden, you can still see the image contribution button, it is not greyed out.

Button is greyed out if you do have NSFW content enabled.

**Comment by LemBurnstein** [comment]
This is fixed!
