### ISSUE TITLE
Create Story Contribution on IPhone - doesn't let you post story if you log in when prompted

### ISSUE THREAD

**Issue by Broderick-Colin** [ImpowerGames/impower#12]
**Create Story Contribution on IPhone - doesn't let you post story if you log in when prompted**
Create Story Contribution on IPhone - doesn't let you post story if you log in when prompted

**To Reproduce**
1. Create a story contribution on a pitch without logging in
2. Log in when prompted.
3. Click "Contribute"
4. Get popup saying "Discard unsaved changes"
5. Keep editing just brings you back to edit screen
6. "Discard" posts the contribution, contribution is missing when you close and revisit the pitch view dialogue.

**Expected behavior**
No popup

**Comment by LemBurnstein** [comment]
Verified issue is closed
