### ISSUE TITLE
Scan username for NSFW content

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#126]
If NSFW:

- Doesn't render anywhere, not next to kudos, not next to contributions, and not on your profile page.

**Comment by LemBurnstein** [comment]
Created a NSFW username that was [flagged]. 
Created a pitch, a contribution, a contribution kudo, and a pitch kudo on the same user.

The username was successfully flagged on the pitch Kudo, but only where it was displayed by the text of the kudo. 
    - However the username was not flagged in the "___ loves this!" area
The username was successfully flagged on the contribution Kudo.
    - Could not verify whether the "__ loves this" section flagged as it wasn't working.
The username was not flagged on the pitch itself.
The username was not flagged on the contribution.
The username was successfully flagged in the "username" section of the user profile page.

**Comment by LemBurnstein** [comment]
See above, all issues resolved
