### ISSUE TITLE
Permission denied error if you create a new project and then immediately try to open it

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#142]
**Describe the bug**
Permission denied error if you create a new project and then immediately try to open it

**Steps To Reproduce**
1. "+ Create Project" on studio page
2. Click on the project you've created
3. See error
4. Pressing refresh ends the issue.

![image](https://user-images.githubusercontent.com/92612567/159187163-ad541f8d-26fc-43ce-8f0e-4738464f8576.png)

**Comment by LemBurnstein** [comment]
Still an issue

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Investigating now

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Seems to be fixed for new users. Old users may receive the error once, but should not encounter it again after that.

**Comment by LemBurnstein** [comment]
Resolved!
