### ISSUE TITLE
"Play" button on game engine only starts if you have a # Section, or starts at the first # Section header

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#143]
**Describe the bug**
"Play" button on game engine only starts if you have a # Section, or starts at the first # Section

**Steps To Reproduce**
1. Write a script without a # Section header, or a script where a character has dialogue prior to the first # Section Header.

**Expected Result**
Some kind of warning telling you to add a # Section header.
Or add a default # Act 1 appears at the start of every new project.
Or make the "Play" button start at either the first section, or the first character dialogue.

**Actual Result**
Game doesn't start when you hit play (if you have no # Section header) or skips the dialogue you wrote prior to the first # Section header.

**Screenshots**
![image](https://user-images.githubusercontent.com/92612567/159189380-f6850143-395b-43fa-ba3a-4a45dfb9dec3.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed by 49ed2cc

**Comment by LemBurnstein** [comment]
Fixed if you have no # Sections, but still skips any dialogue before the first # Section

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed by e74b9d2d

**Comment by LemBurnstein** [comment]
Fixxed!
