### ISSUE TITLE
Adding a "screenplay snippet" after dialogue generates an error.

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#146]
**Describe the bug**
When using the "screenplay snippet" buttons to add sample text while the cursor is at the end of dialogue text generates an error screen.

**Steps To Reproduce**
1. Create a simple script with a section and dialogue (e.g. "Yes.").
2. Click the cursor at the end of your dialogue (e.g. The period at the end of "Yes.") and then click on any of the "screenplay snippet" buttons.

**Expected Result**
The "screenplay snippet" is inserted after the dialogue.

**Actual Result**
An "Application error: a client-side exception has occurred (see the browser console for more information)." error and white screen is generated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.82

**Additional context**
Sometimes this works normally without an error.  However, I'd say I was able to reproduce this bug 70% of the time.

**Comment by lovelle-cardoso** [comment]
@Wipeless Fixed by 33e90d7

**Comment by Wipeless** [comment]
No errors!
