### ISSUE TITLE
Pushing Play on an empty script generates an error

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#152]
**Describe the bug**
An error is generated when attempting to play an empty script.

**Steps To Reproduce**
1. Remove all contents of a script.
2. Push "Play" 

**Expected Result**
Nothing would appear in the game preview.

**Actual Result**
A white screen appears with the following error:
"Application error: a client-side exception has occurred (see the browser console for more information)."

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.84

**Comment by LemBurnstein** [comment]
This works
