### ISSUE TITLE
Assigning variable command doesn't appear to work

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#154]
**Describe the bug**
The "assign variable" command doesn't seem to retain its value.

**Steps To Reproduce**
1. Create the a script that attempts to update a variable using the "assign variable" command (see Screenshot)
2. Push Play

**Expected Result**
The dialogue should display "My character's name is Amy"

**Actual Result**
The dialogue displays "My character's name is Danny". It still uses the original variable value instead of the updated value.

**Screenshots**
![assignVar](https://user-images.githubusercontent.com/1523864/160223498-2dfd2888-09c1-4d5a-935e-316f42add401.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.84

**Comment by lovelle-cardoso** [comment]
@Wipeless Fixed by 5d43ec45

**Comment by LemBurnstein** [comment]
Tested. This one works now!
