### ISSUE TITLE
Last shown dialogue and portrait remains in preview screen when all dialogue is removed and play button is pressed.

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#155]
**Describe the bug**
After playing a preview with dialogue, once all dialogue is removed it still remains in the preview box.

**Steps To Reproduce**
1. Create a script with Dialogue
2. Play the script
3. Verify the Dialogue appears in the Preview Area
4. Stop the script
5. Remove the Dialogue
6. Play the script
7. Observe the Preview area

**Expected Result**
Without any dialogue in the script, the preview screen should be empty.

**Actual Result**
The last dialogue remains in the preview area.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.84 

**Additional context**
This can also be replicated with normal Text without a Dialogue command.  Just have some text in the script, play it, and then remove it.  The text will continue to be visible in the preview area after it's removed.

**Comment by lovelle-cardoso** [comment]
@Wipeless Fixed by 9a99683

**Comment by LemBurnstein** [comment]
Last available image remains in the preview screen when all images are removed from the project

![image](https://user-images.githubusercontent.com/92612567/160300942-90cca929-e8bc-4bed-853c-45f31d590086.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed by f40f32a4

**Comment by Wipeless** [comment]
Is "portrait" different from "image"?  Is `[[image]]` functional?

**Comment by lovelle-cardoso** [comment]
@Wipeless portraits are specified inside dialogue blocks under the character name

CHARACTER 
[[happy]]
This is my house

Images are specified outside of dialogue blocks. They should work. But I'll double check.

**Comment by Wipeless** [comment]
Gotcha.  Seems to work with your example!  How was this reference screenshot in this ticket generated?  I'll keep on testing!

**Comment by LemBurnstein** [comment]
Verified portraits are cleared in the game preview if you delete them in the editor and then press "Game Preview".

Also, dialogue was cleared in the game preview when I deleted it in the editor and then pressed "Game Preview".
