### ISSUE TITLE
Tone doesn't show up in the game preview until you start typing dialogue below it

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#157]
**Describe the bug**
Tone doesn't show up in the game preview until you start typing dialogue below it

**Steps To Reproduce**
1. Go to Engine
2. Type out a character name
3. Type open parenthesis
4. Start typing a tone (I chose "Shouting out the door")
5. Close parenthesis and new line
6. See error

**Expected Result**
The tone (Shouting out the door) shows up in the in the game preview

**Actual Result**
() shows up in the game preview

**Screenshots**
![image](https://user-images.githubusercontent.com/92612567/160256376-8dcafed6-49f7-4576-bf0b-d5c76b67890d.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed by 0a83123c

**Comment by LemBurnstein** [comment]
Tested, Fixed!
