### ISSUE TITLE
Wrong text color for [[ when inserting images into a game behind an if or else statement

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#158]
**Screenshots**
![image](https://user-images.githubusercontent.com/92612567/160256948-c43975b7-9a16-4627-945d-8a883f9e0bc6.png)

**Comment by LemBurnstein** [comment]
This also makes autocomplete not work

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed by 949d08be

**Comment by LemBurnstein** [comment]
Tested, fixed!
