### ISSUE TITLE
Cant scroll down to + Contribution button or to kudo button when on Page View for iPhone without home button 

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#16]
**Describe the bug**
Cant scroll down to + Contribution button or to kudo button when on Page View for iPhone without home button 

**To Reproduce**
1. Open a pitch
2. "Copy Link" to the pitch
3. Open the link to the pitch
4. Bar on bottom of safari browser (back button etc.) blocks the kudo and contribution buttons

**Expected behavior**
Kudo and contribute buttons are immediately visible.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.7.1
 - Browser: Safari
 - Version: 15

**Comment by lovelle-cardoso** [comment]
Should be fixed by #f98a1a4
