### ISSUE TITLE
Deleting the first of two sets of quotations assigned to a variable makes it impossible to create new lines

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#161]
**Describe the bug**
Deleting the first of two sets of quotations assigned to a variable makes it impossible to create new lines

**Steps To Reproduce**
1. Go to Engine / Logic
2. 
# SectionName

var name = "Danny""

4. Try to press enter
5. See error

**Expected Result**
Create new line

**Actual Result**
Expands current line

**Screenshots**
![image](https://user-images.githubusercontent.com/92612567/160261105-85e489da-514e-4b13-816f-4a8d60cf57e1.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein  Fixed by c534adac

**Comment by LemBurnstein** [comment]
Tested, Fixed!
