### ISSUE TITLE
Dynamic section without '|' separator does not display error and crashes runtime

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#171]
**Describe the bug**
When giving the option to use different choices with `{choice1|choice2}`, this works as expected.

However, if I wanted to use a single choice `{choice1}`, this should either still work or an error generates to let me know that this is not a valid way to use braces.

**Steps To Reproduce**
1. Create the following script:
```
# Root

The root

> {First}

^

# First

First try

> Root
```
2. Verify that no errors are generated.
3. Enter Play Mode

**Expected Result**
The script will continue to the `First` section.  Or if this is an invalid use of braces for a single option, then an error should be generated.

**Actual Result**
The script gets stuck on the go-to `>` command.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 99.0.4844.84

**Comment by lovelle-cardoso** [comment]
@Wipeless Fixed by 4424c03f

**Comment by Wipeless** [comment]
Verified!
