### ISSUE TITLE
Default UI for choices not present

### ISSUE THREAD

**Issue by Broderick-Colin** [ImpowerGames/impower#183]
**Describe the bug**
Need to make UI for choices in engine "Play" mode.

**Steps To Reproduce**
1. Go to Engine
2. Reach a choice in the game
3. Choice buttons don't show up, just text. Cannot click on text to advance game

**Expected Result**
Default UI appears for choice

**Screenshots**
![image](https://user-images.githubusercontent.com/92612567/188345498-744760b6-023b-4e06-811f-2ac785f29e92.png)

**Comment by lovelle-cardoso** [comment]
@Broderick-Colin Fixed on test endpoint
