### ISSUE TITLE
thumbs up/down bajillion

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#2]
**Describe the bug**
can click thumbs up/down mult times to bring count super up/down

**To Reproduce**
1. do the mult click
4. thumbs up bajillion

**Expected behavior**
thumbs up/down

**Screenshots**
no

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: samsung galaxy s10e
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Fixed in latest build
