### ISSUE TITLE
Expect profile image to be replicable by clicking on the icon on "Your Account" page

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#29]
**Describe the bug**
Expect profile image to be replicable by clicking on the icon on "Your Account" page

**To Reproduce**
1. Go to Your Account page
2. Click on your profile photo
3. It shades as if it is supposed to be interactable, but nothing happens when you click it.

**Expected behavior**
Clicking on image prompts you to change your profile image

Windows 10, Chrome browser

**Comment by lovelle-cardoso** [comment]
No longer valid with new "Your Account" layout.
