### ISSUE TITLE
layout of cookies page not mobile friendly

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#3]
**Describe the bug**
weird half page

**To Reproduce**
1. Go to cookies page
2. see error

**Expected behavior**
full layout

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: samsung galaxy s10e
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Fixed in latest build
