### ISSUE TITLE
Account name on mobile when you change your account name

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#34]
**Describe the bug**
Account name on mobile when you change your account name

**To Reproduce**
1. Go to "Your Account"
2. Click on edit profile
3. Change your username to a valid username
4. Return to homepage.
5. Click on navigation bar (3 horizontal lines)
6. Old Username is still displayed at bottom of the navigation bar.

**Expected behavior**
Updated Username is displayed at bottom of navigation bar.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS8.1
 - Browser: safari

**Comment by lovelle-cardoso** [comment]
Fixed by 432bf93

**Comment by LemBurnstein** [comment]
Verified that updated username shows up on navigation bar
Verified that all pitches update to the new username
Verified that contributions update to match the new username
HOWEVER Kudos currently do not update to reflect the new username (Username on new kudos also uses your original username)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein This bug only refers to the account name in the mobile navdrawer though. So this should be fixed right? I'll work on fixing #35 for kudos

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Username should properly update for kudos now.

**Comment by LemBurnstein** [comment]
![image](https://user-images.githubusercontent.com/92612567/140247459-ba6f2f9f-f008-41e2-a006-69f6461a0173.png)

![image](https://user-images.githubusercontent.com/92612567/140247511-f817d2d4-b4a2-432a-893b-9c96bf52674e.png)

Cant test, "Your Account" page gets stuck on loading screen, then I get a Client-Side Exception

Browser Console:
![image](https://user-images.githubusercontent.com/92612567/140247628-e2575602-0a83-41b9-994e-d41e8e78fe07.png)

**Comment by LemBurnstein** [comment]
Tried opening again, got infinite loading wheel when selecting contributions

![image](https://user-images.githubusercontent.com/92612567/140247797-ef636e0e-d2e5-4f54-aee1-dece4f4686a7.png)

Verified Username properly updates on kudos.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein bug seems unrelated to this one. Can this one be closed?

**Comment by LemBurnstein** [comment]
Now Pitches, Contributions and Kudos don't update when you update your profile

**Comment by lovelle-cardoso** [comment]
Seems to be a problem on Google's end: https://github.com/firebase/firebase-admin-node/issues/1487

Downgraded all endpoints to firebase-admin@9.11.0 for the time being while they sort it out.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Try again now and see if it works again

**Comment by LemBurnstein** [comment]
Verified that pitches, contributions, kudos, and navigation bar all update to reflect new username.
