### ISSUE TITLE
Cannot visit the profile of users who change their username by clicking on their old contributions

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#35]
**Describe the bug**
Cannot visit the profile of users who change their username by clicking on their old contributions

**To Reproduce**
1. Change your username by editing the "Your Account" page
2. Click on a former post you made with the old account name
3. Endless loading wheel

**Expected behavior**
Former posts get updated to use your new username
oblem.

**Smartphone (please complete the following information):**
 iPhone 11, Safari

**Comment by lovelle-cardoso** [comment]
Fixed by 432bf93

**Comment by LemBurnstein** [comment]
Refer to issue #34, clicking on the kudo of a user who has changed their username still gives you the endless loading circle

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Username should properly update for kudos now.

**Comment by LemBurnstein** [comment]
Confirmed username properly updates for Kudos now.
