### ISSUE TITLE
Permission errors when creating multiple users

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#37]
**Describe the bug**
Permission errors appear when every other new user is created.

**To Reproduce**
1. Create a new user.
2. Create new content that will post to the server (e.g. create post, follow  user, change profile, etc).
3. Log out
4. Create another new user.
5. Create new content that will post to the server (e.g. create post, follow  user, change profile, etc).

**Expected behavior**
The post is successful.

**Actual behavior**
The post is fails with user permission errors displayed in the app and in the console.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.54

**Additional context**
I'm not sure if I can get this consistently to happen, but it seems to happen at least over 50% of the time whenever another user is created.

**Comment by Wipeless** [comment]
@lovelle-cardoso Hrmm still seems to occur.  This was after waiting 24 hrs from creating a user.

I created a user,  make a pitch, updated my profile icon, and then logged out.

When I created a second user afterwards, I received a permission error when I performed a "like" on a pitch.

Is there a time limit on how long I have to wait before creating a new user?

I did all the above in probably less than 4 minutes.

**Comment by Wipeless** [comment]
If it helps, after I created my new second user I received these errors after the user creation flow:
![newUser](https://user-images.githubusercontent.com/1523864/139539807-ba50200e-124f-474e-ba73-3d2b92925da5.png)



Later, when I clicked on the "like", I received the permission error.

**Comment by lovelle-cardoso** [comment]
@Wipeless I think I've figured out what was causing this bug. Can you check this on dev now and see if it's fixed?

**Comment by Wipeless** [comment]
@lovelle-cardoso  Hrmmm, unfortunately I still get the permission error.  Specifically, I still get the "403" error in one of the screenshots I posted earlier.

**Comment by LemBurnstein** [comment]
I made 3 accounts and did not get a permissions error when posting pitches, story contributions, kudos, or kudos on comments.

I think whatever Lovelle did has resolved this issue?

**Comment by Wipeless** [comment]
Looks fixed! Closing!
