### ISSUE TITLE
dark mode: following is following me!

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#4]
**Describe the bug**
following is following me!

**To Reproduce**
1. Go on dark mode
2. scroll down pitch page

**Expected behavior**
not following

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: samsung galaxy s10e
 - OS: 
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Not reproducible on latest build.
