### ISSUE TITLE
Player profile image doesn't appear on mobile

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#40]
**Describe the bug**
When viewing a profile page, the user's profile image is cut off.

**To Reproduce**
1. Use a mobile phone. 
2. Sign in as a user.
3. View your profile page.

**Expected Result**
You can see your profile page which includes your profile image.

**Actual Result**
The profile image is missing or cut off.

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/1523864/139004524-8d183069-b12d-4820-b568-b186a3df04a3.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14.8
 - Browser: Chrome
 - Version: 95.0.4638.50

**Comment by lovelle-cardoso** [comment]
@Wipeless This is intentional. The profile image appears at the bottom of the hamburger menu navdrawer.

**Comment by Wipeless** [comment]
The icon now appears in the new account page layout!
