### ISSUE TITLE
Player profile Image replacement doesn't immediately apply itself

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#41]
**Describe the bug**
After successfully uploading a player profile image,  replacing the image doesn't appear on the profile page until the user navigates away to a different screen.

**To Reproduce**
1. With a signed in user, upload a profile image.
2. Verify that the image has updated in both the top right profile icon and the main profile image page.
3. Edit the profile again and replace the image with a new image.

**Expected Result**
The profile page displays your most recent profile image.

**Actual Result**
The profile page displays your previous profile image.

**Screenshots**
![profile1](https://user-images.githubusercontent.com/1523864/139005980-409476fc-49c5-403e-9055-b1c7e8bd0059.png)

![profile2](https://user-images.githubusercontent.com/1523864/139006005-1e6fad94-ee60-452e-b7b0-0000a8d393f1.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 95.0.4638.54

**Additional context**
This can be solved by navigating away to the Pitch page and then returning to the profile page.  Then, the image updates to the newest image.

**Comment by lovelle-cardoso** [comment]
Fixed by 432bf93

**Comment by Wipeless** [comment]
Confirmed that this is working!
