### ISSUE TITLE
Accessing profile page sometimes causes a mid screen popup

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#42]
**Describe the bug**
When attempting to view the profile page, the account popup appears in the center of the screen.

**To Reproduce**
1. View your profile page

**Expected Result**
You transition to the profile page without any popups on screen.

**Actual Result**
The "Your Account" popup appears in the middle of screen.

**Screenshots**
![account](https://user-images.githubusercontent.com/1523864/139007087-c23689ef-9137-49e1-84b9-7d69a5b99c7f.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 95.0.4638.54

**Additional context**
I'm not sure if it's more noticable for accounts with more information (e.g. more followed users, profile image, etc).

**Comment by lovelle-cardoso** [comment]
@Wipeless Can't seem to replicate this. How are you accessing the profile page and what screen resolution were you viewing the app with?

**Comment by Wipeless** [comment]
@lovelle-cardoso Ah ha!  I've found that I can consistently make this happen when dev tools is open.  

It doesn't seem to occur under normal viewing in the browser.

Closing.
