### ISSUE TITLE
Reporting a user hangs

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#45]
**Describe the bug**
When attempting to report a user, when submitting the report the loading button spins forever. 

**To Reproduce**
1. Go to the Pitch board.
2. Select a user.
3. Report the user.
4. Fill out the report form (I used the `Harassment` reason)
5. Submit

**Expected Result**
The report submits.

**Actual Result**
The report submission button spins and the screen hangs indefinitely.

**Screenshots**
![report1](https://user-images.githubusercontent.com/1523864/139383942-26b841ee-d57f-45a3-8228-92be6453ad98.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.54

**Comment by lovelle-cardoso** [comment]
@Wipeless Can't replicate this. Can you try again now?

**Comment by Wipeless** [comment]
Looks fixed! Closing!
