### ISSUE TITLE
Only require captcha check for signup not login

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#46]
**Is your feature request related to a problem? Please describe.**
It's frustrating for the user to have to answer the captcha challenge every time they log in.

**Describe the solution you'd like**
Only require captcha for signup not login.

**Describe alternatives you've considered**
Tried making the captcha easier, but still seems to require manual input more often than I'd like.

**Comment by Wipeless** [comment]
@lovelle-cardoso Hrmmm, using `dev.impower.games` I do not see the initial captcha upon signing up. Is this expected?

I do see the captcha using `impower.app`.

**Comment by Wipeless** [comment]
Gotcha.  Confirmed that the captcha only appears upon the initial signup!
