### ISSUE TITLE
Allow user to delete their account from their account page

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#47]

**Comment by Wipeless** [comment]
@lovelle-cardoso I can delete my user account.  Is it expected that I can recreate it using the same credentials?  Should I still see the posts of my original user that was deleted?

**Comment by lovelle-cardoso** [comment]
@Wipeless Yes you can recreate it using the same credentials. After your account is deleted, your posts will still be there, but they should be disassociated from your account (username should be displayed as [deleted]).

**Comment by LemBurnstein** [comment]
If you delete your account (I made an account called goodyboy) and then make a new account with the same email address and username, the "Your Account" page only shows a "Connect" button, not an "Edit Profile" button.

Waiting a few minutes and refreshing the page brings back the "Edit Profile" button.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein There's not too much I can do about this since most all our pages are served from the cache, only recached every 60 seconds, and only attempt to update the page if the user refreshes the page (we don't constantly query the server for real-time profile updates on the profile page).

**Comment by LemBurnstein** [comment]
Deleted Google
