### ISSUE TITLE
Allow user to request their data from their account page

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#48]
The request should appear in the realtime database under `exports/<uid>`

**Comment by LemBurnstein** [comment]
I sent a request for LemBurnstein4's user data.

Please confirm this has been recieved

**Comment by lovelle-cardoso** [comment]
@LemBurnstein request received for `goodboy` and `LemBurnstein3` there's a third request in there but can't find a corresponding user doc with that ID. Did you delete your account after requesting data?

![Screenshot_20211103-223355_Samsung Internet](https://user-images.githubusercontent.com/7256621/140263690-2ca36247-9e8c-465b-9d8e-e148cc06840c.jpg)

**Comment by LemBurnstein** [comment]
Verified this works
