### ISSUE TITLE
Make it more obvious that you can use markdown to format your story contribution

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#49]

**Comment by LemBurnstein** [comment]
Verfified that this information was present when making a story contribution:

Note: ` character doesn't exist on iphone keyboard.

Words between angle brackets disappear when it following a line containing another markdown command, not sure if this is a feature:
**iuahduhw**
<adoiwjiufiuweg> 
// adoiwjiufiuweg doesn't display
