### ISSUE TITLE
clicking 2:1 on horizontal photos shoves photo to side

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#5]
**Describe the bug**
title

**To Reproduce**
1. upload photo
2. edit to 2:1

**Expected behavior**
not do that

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy se10
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Fixed in latest build
