### ISSUE TITLE
Allow filtering contributions by type

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#52]
Add "Type" dropdown to contribution list header that allows you to filter the contribution list by type (Pitch, Story, Image, Audio)

**Comment by LemBurnstein** [comment]
Filtering by a type of contribution that hasn't been contributed to the pitch creates infinite loading wheel

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Forgot to deploy the composite index (as usual!) Should be fixed now.

**Comment by LemBurnstein** [comment]
This worked for the pitch "Drift Away"

When I tried clicking the filter dropdown on "Wheeling and Dealing" the pitch closed and brought me back to the top of the page. When I tried scrolling down this weird gap in the pitches appeared (Scrolling down a lot I could find more pitches below the gap)

Tested this 3 times and got the same bug
![image](https://user-images.githubusercontent.com/92612567/140254351-a92ed81f-a345-4abf-9fb3-975aaabfbd55.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Opened separate bug for that issue #58

**Comment by lovelle-cardoso** [comment]
@LemBurnstein #58 should be fixed

**Comment by LemBurnstein** [comment]
Verified you can filter contributions by type
