### ISSUE TITLE
Display a user's pitches and contributions on their profile page

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#54]

**Comment by LemBurnstein** [comment]
Click on the username "LemBurnstein4" on the pitchboard.
Click on the contributions tab
See all the contributions I've made
Attempting to scroll downward makes the contributions bug out and disappear, leaving the contributions tab blank

Cant seem to replicate bug by following link to user account page, need to go to user page from pitchboard
https://dev.impower.app/u/LemBurnstein4
