### ISSUE TITLE
On Mobile, unable to play audio files uploaded as .ogg format

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#55]
**Describe the bug**
When using a mobile device, an audio contribution uploaded as a .ogg does not play.

This format does play on the desktop app.

**To Reproduce**
1. On a pitch, add an audio contribution of type .ogg.
2. On the desktop app, verify that this file can be played back.
3. On a mobile device, attempt to play this audio file.

**Expected Result**
The audio file plays.

**Actual Result**
The "play" icon is pressed and changes to the "pause" icon, but the playback never progresses.

**Smartphone (please complete the following information):**
 - Device: iPhoneSE
 - OS: iOS 14.8
 - Browser: Safari
 - Version: 14

**Additional context**
Other audio formats can be played on mobile.

**Comment by lovelle-cardoso** [comment]
@Wipeless Safari doesn't support ogg. Will have to take it up with Apple, my dude! https://www.w3schools.com/html/html5_audio.asp
