### ISSUE TITLE
Can access account page for all potential username

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#56]
**Describe the bug**
Can access an account page for a username even if that username doesn't exist

**To Reproduce**
1. go to https://dev.impower.app/u/LemBurnsteinsFakeAccount
2. Page opens
![image](https://user-images.githubusercontent.com/92612567/140248242-e6c8ad38-48d0-4943-8817-bbc052c0d0dc.png)

**Expected Result**
Only pages for real users should open

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  chrome

**Comment by LemBurnstein** [comment]
Potential Vulnerability: Can you inject code like this?
![image](https://user-images.githubusercontent.com/92612567/140248476-91cb4efc-16ec-4314-96a6-2e7701cf5361.png)

No limit to the length of the account slug

**Comment by lovelle-cardoso** [comment]
> Potential Vulnerability: Can you inject code like this? ![image](https://user-images.githubusercontent.com/92612567/140248476-91cb4efc-16ec-4314-96a6-2e7701cf5361.png)
> 
> No limit to the length of the account slug

No will just be displayed as a string.
