### ISSUE TITLE
404 error when clicking "Impower" homepage button from account page

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#57]
**Describe the bug**
404 error when clicking "Impower" homepage button from account page

**To Reproduce**
1. Go to "Your Account"
2. Click here 
![image](https://user-images.githubusercontent.com/92612567/140251519-bb6a4ed7-0950-4fa4-9f07-b58ad4106306.png)

3. 404 error 
![image](https://user-images.githubusercontent.com/92612567/140251560-c11573c8-bd3b-4370-b748-6d097af3e3db.png)

**Expected Result**
Land on Impower Home Page

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by LemBurnstein** [comment]
Works when you are in the "Edit Account" flow.

**Comment by TripleAC** [comment]
It fixed
