### ISSUE TITLE
Opening a popover menu on desktop causes window to scroll to top

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#58]
**Describe the bug**
If you scroll down the pitch page, and then open any popover menu (like the filter menu or option menu) on desktop, it causes the window to scroll all the way to the top.

**To Reproduce**
1. Go to /pitch on desktop
2. Scroll down
3. Click a pitch to open it
4. Click the vertical ellipsis to open the menu

**Expected Result**
Popover menu opens and window scroll position is maintained

**Actual Result**
Window in the background of the opened pitch scrolls all the way to the top (to the first pitch) which you notice once you close the pitch.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by LemBurnstein** [comment]
Confirmed that I could open the contributions popover menu after scrolling down the pitch page
