### ISSUE TITLE
can's scroll back up on following tab; stuck on adorable prof

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#6]
**Describe the bug**
title

**To Reproduce**
1. click following
2. scroll down all the way
3. trigger prof
4. cant scroll up

**Expected behavior**
scroll up

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy se10
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Fixed in latest build
