### ISSUE TITLE
Unable to close "Sign Up" popup after user creation error

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#60]
**Describe the bug**
If you commit an error during the user creation popup, you are unable to close the popup.

**To Reproduce**
1. Start signed out of a profile.
3. Click "Sign Up" in the upper right of the screen to create a new user.
4. Enter information that would give an error in the user creation flow (e.g. invalid email or username)
5. Click "Sign Up" to attempt to create the user.
6. Witness errors.
7. Attempt to close the "Sign Up" popup by pushing the "X" on the the popup.

**Expected Result**
The user can exit the sign up flow popup.

**Actual Result**
The user is stuck on the sign up popup box.  Even if the errors are resolved, they cannot exit until they create a new user or refresh the page. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by lovelle-cardoso** [comment]
@Wipeless Can't replicate this. Can you try again now?

**Comment by lovelle-cardoso** [comment]
@Wipeless Nevermind! replicated it

**Comment by Wipeless** [comment]
Fixed!
