### ISSUE TITLE
Changing username twice in a row - get "permission denied"

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#61]
**Describe the bug**
Changing username twice in a row - get "permission denied"

**To Reproduce**
1. Go to account page
2. Change username
3. make a pitch
4. Attempt to change username again
5. "Permission denied"
6. Going to your public profile page shows "User doesn't exist"

**Expected Result**
Can successfully change username

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:  chrome

**Comment by Wipeless** [comment]
Looks good!
