### ISSUE TITLE
Editing Kudo after changing username uses the old username

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#62]
**Describe the bug**
Editing Kudo after changing username uses the old username

**To Reproduce**
1. Log in
2. Create a Kudo
3. Change account name
4. Edit former kudo shortly after changing account name.
5. Edited Kudo posts with old account name

**Expected Result**
Edited Kudo posts with updated account name

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by lovelle-cardoso** [comment]
@LemBurnstein This should be fixed now

**Comment by LemBurnstein** [comment]
Get permission denied warning when trying to change username

**Comment by LemBurnstein** [comment]
I made a new account and this worked
