### ISSUE TITLE
Can't edit contributions

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#63]
**Describe the bug**
Cant edit contributions

**To Reproduce**
1. Create a story contribution
2. Attempt to edit story contribution
3. Endless loading wheel

**Expected Result**
Editable text window opens 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Comment by Wipeless** [comment]
Looks good!

**Comment by LemBurnstein** [comment]
This works now
