### ISSUE TITLE
Add "Your Connections" page where a user can view their connections and connection requests

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#64]

**Comment by Wipeless** [comment]
Looks good!

If User A and User B are connected, what's the expected behavior if User A unconnects with User B?

Right now, I see User A sees a request from User B.  While User B no longer sees the connection to User A.  Is this expected?

**Comment by lovelle-cardoso** [comment]
@Wipeless That's expected. Though, maybe I should add one more tab for "PENDING" so a user can see all their pending requests (so it's clear the connection got moved back to pending rather than just suddenly disappearing)

I should probably also display a notification if a user disconnects with you after you've both connected.

**Comment by lovelle-cardoso** [comment]
@Wipeless Ok so renamed requests tab to "INCOMING" and added "OUTGOING" requests tab.

I didn't add a notification but I think this should be enough? Let me know what you think.

**Comment by LemBurnstein** [comment]
PERMISSION DENIED error when I try to cancel outgoing connection requests from the connections page

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Canceling outgoing connection requests should be fixed now

**Comment by LemBurnstein** [comment]
This works now
