### ISSUE TITLE
Retracted "Connect" request notification still appears

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#66]
**Describe the bug**
If User A attempts to connect to User B, but then later changes their mind, User B continues to see the notification from User A.

**To Reproduce**
1. Login as User A
2. From a pitch, attempt to form a connection with User B by pushing the "Connect" button.
3. Push the "Connect" button to undo the attempt.
4. Log out of User A.
5. Login as User B.

**Expected Result**
Upon logging in as User B, they do not see the connection attempt from User A.

**Actual Result**
Upon logging in as User B, they see a notification from User A.  When attempting to view, the request is not available.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by LemBurnstein** [comment]
Tested this, it seemed to work
