### ISSUE TITLE
Contributing additional images/audio creates new contributions and errors.

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#69]
**Describe the bug**
Instead of replacing existing images or audio, a user has the option to contribute another media file. This generates a permission-denied error and gives an incorrect number of contributions for a pitch.

**To Reproduce**
1. On a pitch, add an image or audio contribution by pushing the "+" button.
2. Complete the upload flow.
3. Click away to return back to the main Pitch page.
4. Select the same pitch that you made the contribution to.
3. On the same pitch, add the same type of media by pushing the "+" button.
4. Click the "Contribute" button on the upload flow instead of the "Replace" button.

**Expected Result**
You cannot contribute more than one type of media.

**Actual Result**
You replace your existing media file. However, you receive a "Permission-Denied" error.  The contribution count now thinks there's two contribution instead of the replace single contribution.

**Screenshots**
![replace1](https://user-images.githubusercontent.com/1523864/140874325-0b35dd26-8322-46ef-80e4-7ae346f42c95.png)

![replace2](https://user-images.githubusercontent.com/1523864/140874743-aa1ae9ca-8101-4ae0-a035-5a726219fad2.png)

![replace3](https://user-images.githubusercontent.com/1523864/141229499-68ce54b7-12d8-4ac2-bad6-c1811a2eedac.png)

![replace4](https://user-images.githubusercontent.com/1523864/141229511-dacc0869-371d-4947-8083-fd659be12439.png)

![replace5](https://user-images.githubusercontent.com/1523864/141229517-8586e7fd-21fb-4eea-9a78-5be2617a65d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Additional context**
Instead of having the "Replace" button at the very bottom, perhaps replace it with the "Contribution" button when a media file already exists?

**Comment by lovelle-cardoso** [comment]
@Wipeless Hm if you open the contribute menu after submitting an image contribution, the image contribution button should be greyed out so you can't submit another one. So I'm not sure how you managed to create another image contribution on the same pitch. I may need more specific repro steps for this one.
![ContributeMenu](https://user-images.githubusercontent.com/7256621/141169768-67bcc12b-6b6a-4b67-9e1f-a46921a12cc2.PNG)

**Comment by LemBurnstein** [comment]
I also cannot replicate Danny's ability to contribute multiple images

**Comment by Wipeless** [comment]
@lovelle-cardoso  @LemBurnstein  I've updated the instructions to recreate this bug.  Make sure after uploading the first contribution, click AWAY from the pitch to return to the main pitch page.  Then when you select the pitch again, the "+" button will allow for an image/audio to be uploaded again.

I've added more screenshots showing an image example.

**Comment by lovelle-cardoso** [comment]
@Wipeless Was able to repro with those steps. Working on the fix now

**Comment by lovelle-cardoso** [comment]
@LemBurnstein @Wipeless Should be fixed now!

**Comment by LemBurnstein** [comment]
Followed Danny's steps, was not able to upload a new image after uploading the first image and going back to the pitchboard
