### ISSUE TITLE
mobile app button on main page 404s

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#7]
**Describe the bug**
title

**To Reproduce**
1. click mobile app

**Expected behavior**
just don't

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy se10
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Removed mobile app button on mage page
