### ISSUE TITLE
Changing username while profile image uploads causes a 403 error.

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#70]
**Describe the bug**
While uploading a new user profile image, an error generates when attempting to also change the username.

**To Reproduce**
1. Go to your user profile and edit.
2. Upload a profile image. A large image may help test this bug.
3. While the image is uploading, quickly attempt to modify your username.
4. Submit your username.

**Expected Result**
You can update your username.  Or, you cannot make any changes until the image upload completes.

**Actual Result**
A 403 error generates.  The username, however, continues to save.

**Screenshots**
![uploadProfile](https://user-images.githubusercontent.com/1523864/140876749-c84dc9fe-e4b4-4ec6-95a6-9674f7f2e0de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by lovelle-cardoso** [comment]
@Wipeless This should be fixed now

**Comment by LemBurnstein** [comment]
Getting a permission denied error when I try to change my username (changed it 4 times in a row while trying to replicate this bug)

**Comment by Wipeless** [comment]
@LemBurnstein  @lovelle-cardoso This bug appears to be fixed and I do not see the permission denied errors.  Is this a new bug?  Should I close out this issue?

**Comment by lovelle-cardoso** [comment]
@LemBurnstein @Wipeless I found the problem that was causing the issues with updating your user information multiple times. Should be deployed in a few minutes.

**Comment by LemBurnstein** [comment]
I was able to change my username while uploading a new profile photo.
