### ISSUE TITLE
Submitting report returns back to report page.

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#71]
**Describe the bug**
After submitting a report, it returns to the same report page.  Since all the information is already entered, it can be confused with the report failing to send.

**To Reproduce**
1. Select a user or pitch element.
2. Report the object.
3. Complete the Report flow and submit.

**Expected Result**
The screen will navigate away from the Report page after the report is submitted. 

**Actual Result**
The screen remains on the report page with the form still populated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by lovelle-cardoso** [comment]
@Wipeless I added a "Return to previous page" button that appears after a report is successfully submitted. Also all fields and the submit button are disabled upon submission so it should be clearer that your support was submitted

**Comment by Wipeless** [comment]
Great! Works!
