### ISSUE TITLE
Permission denied when replacing image and additional contribution

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#73]
**Describe the bug**
When replacing an existing contribution image, the user receives a "permission denied" error.  The image still is replaced. But although there's only  one image displayed, the contribution tally is marked as two.

**Steps To Reproduce**
1. Select a pitch that you haven't contributed to yet.
2. Contribute an image.
3. Once the image is uploaded, do not click away from the pitch.
4. Select your contribution and select Edit.
4. In the edit popup, select "Replace File"
5. Select a different image.
6. Select "Contribute"  (NOTE: this should normally say "Submit")

**Expected Result**
The image is replaced without errors.  The user also receives a warning that their score will be reset. The contribution count only adds 1 for your contribution.

**Actual Result**
The image is replaced, but a "Permission Denied" error appears and there's no warning that the score will be reset. The contribution count also adds 2 for your single contribution.

The following error in the console:

POST https://firestore.googleapis.com/v1/projects/impowergames-dev/databases/(default)/documents:commit 403

@firebase/firestore: Firestore (9.0.0_lite): RestConnection Commit failed with error:  {"code":"permission-denied","name":"FirebaseError"} url:  https://firestore.googleapis.com/v1/projects/impowergames-dev/databases/(default)/documents:commit request: {"writes":[{"update":{"name":"projects/impowergames-dev/databases/(default)/documents/pitched_games/cai7389bDf5YazJ7fZzCXa/contributions/PxrxJlVX00cQZNnKND1kHQZGSQh2-image"

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69 

**Additional context**
This only seems to happen if it's your very first image contribution and your very first replacement edit for this image.

**Comment by LemBurnstein** [comment]
Tested, this seems to work consistently now
