### ISSUE TITLE
Instagram link generates an "Opps, an error occurred" error.

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#76]
**Describe the bug**
Clicking on any of the Instagram links from the main footer or pateron page generates a "Opps, an error occurred" error.

**Steps To Reproduce**
1. From any page where the Instagram icon is displayed (e.g. main footer, donation page), click on the Instagram icon.

**Expected Result**
The page navigation continues to the Instagram page.

**Actual Result**
An error appears.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by lovelle-cardoso** [comment]
@Wipeless Hmm can't seem to replicate this?

**Comment by Wipeless** [comment]
Hrmmm, here's some additional screenshots:

![instagram1](https://user-images.githubusercontent.com/1523864/141927249-00221313-9e79-48dc-8ce2-9f3ef2cdd7ff.png)

![instagram2](https://user-images.githubusercontent.com/1523864/141927277-f2ee59ab-024f-42c7-bed1-57008ad5bbe0.png)

![instagram3](https://user-images.githubusercontent.com/1523864/141927295-aaed58b0-090f-42a3-89ca-615518bda28d.png)

**Comment by Wipeless** [comment]
@lovelle-cardoso Ahh ok! Looks like it was an Instagram issue.  I was logged in with an old account which I guess the password was changed on another device (since I don't use Instagram on browser that much).  Logging out and then logging back in on Instagram resolved this. Closing!
