### ISSUE TITLE
Still says "Story Submitted" or "Image Submitted" when you delete a story or an image contribution

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#78]
**Describe the bug**
Still says "Story Submitted" or "Image Submitted" when you delete a story or an image contribution

**Steps To Reproduce**
1. Open an existing pitch on the pitchboard
2. Contribute a story or an image contribution
3. Close the pitch card
4. Open the pitch card
5. Delete your contribution
6. Click on the + icon
7. Still says "Story Submitted!" or "Image Submitted!"

**Expected Result**
Allowed to post a new story or image contribution.

**Comment by LemBurnstein** [comment]
Now you can submit more stories or images, but you cant see them once they are submitted

**Comment by LemBurnstein** [comment]
You can continue submitting stories and images ad nauseum.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein K should be fixed now

**Comment by LemBurnstein** [comment]
This works now
