### ISSUE TITLE
main page buttons are a disaster

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#8]
**Describe the bug**
title

**To Reproduce**
1. click the main page buttons

**Expected behavior**
not be a disaster

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy se10
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Removed download buttons
