### ISSUE TITLE
Title changes between steps of the pitch creation flow

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#80]
**Describe the bug**
Title changes between steps of the pitch creation flow

**Steps To Reproduce**
1. Open Pitch creation flow
2. select tags, click next
3. see a title suggestion autopopulate, click next
4. Add description, click next
5. Select inspiration, click next
6. Different title appears on pitch card than was autopopulated

**Expected Result**
Title remains the same as you switch between steps on the pitch creation flow

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:  chrome

**Comment by lovelle-cardoso** [comment]
Fixed by 0c4c3b4

**Comment by LemBurnstein** [comment]
This appears to be fixed
