### ISSUE TITLE
Tags deselected in the P.I.G. when editing a pitch 

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#81]
**Describe the bug**
Tags deselected in the P.I.G. when editing a pitch 

**Steps To Reproduce**
1. Click "edit pitch" on a pitch
2. Accept existing tags, click next
3. Click on lightbulb by title generator
4. No title suggestions because all tags are deselected by default when editing a pitch.

**Expected Result**
All tags are selected in pitch generator, giving the P.I.G. something to work with

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Comment by lovelle-cardoso** [comment]
Fixed by 0c4c3b4

**Comment by LemBurnstein** [comment]
This seems to work!
