### ISSUE TITLE
Permission denied error when downvoting new contributions

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#82]
**Describe the bug**
Permission denied error when downvoting new contributions

**Steps To Reproduce**
1. Open a pitch on the pitchboard
2. Create a story contribution
3. Attempt to downvote the story contribution
4. Permission denied error

**Expected Result**
Downvote is allowed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Can't replicate this one. Does it only happen if you downvote very quickly after creation? What if you wait a few seconds?

**Comment by lovelle-cardoso** [comment]
This was a race condition in the server. Fixed by allowing count to go negative if very first decrement arrives before first increment

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Ok this should be fixed now (for real)

**Comment by LemBurnstein** [comment]
This is fixed!!!
