### ISSUE TITLE
Banned users should have all posts delisted

### ISSUE THREAD

**Issue by lovelle-cardoso** [ImpowerGames/impower#83]
Post Moderation Actions
---
(initiated on post by mod)

removed = delisted, hidden
flagged = temporarily display [flagged] instead of content while the user is resolving issue, and send them a warning

Post User Actions
---
(initiated on post by user)

deleted = delisted, content expunged, post anonymized (author username and icon is expunged)

Account Moderation Actions
---
(initiated on account by admin)

muted = can't write
suspended = can't write, all posts delisted
banned = can't write, all posts delisted, all post content hidden
flagged = temporarily display [flagged] instead of content while the user is resolving issue, and send them a warning

Account User Actions
---
(initiated on account by user)

deleted = all posts are anonymized (author username and icon is replaced with [deleted]). post content will still be visible unless the user explicitly deletes their post before deleting their account.

---

When you are banned:

- All of your pitches, contributions, and kudos with text should be delisted (should no longer appear in any list or search)
- Your delisted pitches, contributions, and kudos with text can still be accessible by direct link but their content should be replaced with "[removed]"

When you are un-banned:

- All of your pitches, contributions, and kudos with text _that have not been explicitly deleted or removed_, should be relisted again (should appear in lists or searches)
- Your relisted pitches, contributions, and kudos with text _that have not been explicitly deleted or removed_, should have their content visible again

**Comment by LemBurnstein** [comment]
Banning works
