### ISSUE TITLE
sometimes clicking contribute story takes you to trending page then opens up story

### ISSUE THREAD

**Issue by TripleAC** [ImpowerGames/impower#9]
**Describe the bug**
above

**To Reproduce**
1. do thing

**Expected behavior**
don't

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy se10
 - Browser samsung internet
 - Version 15.0.2.47

**Additional context**

**Comment by lovelle-cardoso** [comment]
Fixed in latest build
