### ISSUE TITLE
Deleting pitch in pop-up view on pitchboard creates wonky placement of existing pitches. 

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#91]
**Describe the bug**
Deleting pitch in pop-up view on pitchboard creates wonky placement of existing pitches. 

![image](https://user-images.githubusercontent.com/92612567/144729212-b9ab7fba-dc90-4444-b0af-55907788f80d.png)

**Comment by LemBurnstein** [comment]
This also sometimes gives you a permission error.

**Comment by LemBurnstein** [comment]
Permission denied error happens for all project types whether or not the pop up view is opened

**Comment by LemBurnstein** [comment]
No more permission error.
Waiting on Wonk fix

**Comment by LemBurnstein** [comment]
Still a little wonky, but now it redirects you to the pitch page view instead of trapping you on the wonky screen

**Comment by LemBurnstein** [comment]
This also happens if you open up a contribution inside the profile page and delete it there.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Hid the wonkiness under a loading screen

**Comment by LemBurnstein** [comment]
Wonk has been de-wonked!

**Comment by LemBurnstein** [comment]
This is back (briefly) if you delete a contribution from the popup view in the profile page

**Comment by LemBurnstein** [comment]
Wow! Wonk was wemoved!

**Comment by LemBurnstein** [comment]
I'm sorry for that
