### ISSUE TITLE
"All" projects option in dropdown menu on profile page

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#93]
"All" projects option in dropdown menu on profile page
![image](https://user-images.githubusercontent.com/92612567/144731852-49a74eb8-aa45-435a-aa52-e1377a5e9c17.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Made it possible to view all project types (on both profile and pitches page)

**Comment by LemBurnstein** [comment]
This feature has been tested.
