### ISSUE TITLE
Monitor this to see if just a caching thing - Editing environment from page view - shows duplicate environment pitch

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#96]
**Describe the bug**
![image](https://user-images.githubusercontent.com/92612567/144734000-b2ec05cc-860d-4182-b484-c2434af6e30d.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Not able to replicate this. Can you check again?

**Comment by LemBurnstein** [comment]
I can no longer replicate this
