### ISSUE TITLE
Endless back arrow loop

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#97]
**Describe the bug**
Endless back arrow loop

**Steps To Reproduce**
1. Go to pitchboard
2. Open a pitch
3. Create a contribution
4. Click on contribution (opens popup window)
5. Delete contribution from inside of popup window
6. Taken to page view of deleted contribution
7. Click back arrow
8. Taken to page view of pitch
9. Click back arrow
10. Taken to page view of deleted contribution (Repeats forever)

**Expected Result**
Clicking back arrow on page view takes you to the pitchboard.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by LemBurnstein** [comment]
Also happens if you delete contribution from page view

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Fixed!

**Comment by LemBurnstein** [comment]
This works now!
