### ISSUE TITLE
Trending page is empty after pitching a game to the "All" catagory

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#98]
**Describe the bug**
Trending page is empty after pitching a game to the "All" category

**Steps To Reproduce**
1. Go to the "All" pitchboard
2. Click the pitch button and create a game pitch
3. Post the game pitch
4. Press back arrow on page view page
5. Returns to the "All" pitchboard, but the trending page is empty unless you refresh the page

**Expected Result**
Trending page is populated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by LemBurnstein** [comment]
Also happens if you refresh the page while looking at All

**Comment by LemBurnstein** [comment]
Now if you press the back arrow, only the most recent pitch is shown.

Refreshing when on the page with only the most recent pitch returns the blank page.

**Comment by lovelle-cardoso** [comment]
@LemBurnstein Server side rendering static props was not accounting for "all" type. Should work now.

**Comment by LemBurnstein** [comment]
This works as expected now!
