### ISSUE TITLE
Posting a contribution to a Voice pitch while in the "All" menu takes you to a mostly empty page instead of staying in the popup view for the pitch.

### ISSUE THREAD

**Issue by LemBurnstein** [ImpowerGames/impower#99]
**Describe the bug**
Posting a contribution to a Voice pitch while in the "All" menu takes you to a mostly empty page instead of staying in the popup view for the pitch.

**Steps To Reproduce**
1. Go to "All" pitchboard
2. Click on a pitch to open the popup view
3. Add a contribution to the pitch
4. Taken to mostly empty page

![image](https://user-images.githubusercontent.com/92612567/145517744-c9155329-8a77-47aa-9420-94d4db701592.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by LemBurnstein** [comment]
Deleting a contribution on a popup page in the "All" pitchboard creates a similar blank page (but the page is stuck on "loading")

![image](https://user-images.githubusercontent.com/92612567/145519174-b59c911c-95cb-432e-a029-f35ba7895bc4.png)

**Comment by LemBurnstein** [comment]
Deleting a pitch from the "all" pitchboard in the popup view and then pressing the back arrow takes you to a mostly blank page

![image](https://user-images.githubusercontent.com/92612567/145519434-8b1ed107-43d6-49d6-b4dd-ae4371325521.png)

**Comment by LemBurnstein** [comment]
Kudoing a pitch from the popup view takes you to the mostly empty page

![image](https://user-images.githubusercontent.com/92612567/145519666-333e6fc9-94a7-4073-abf5-6e0f4d224a1b.png)

**Comment by LemBurnstein** [comment]
Also happens on Mobile

![image](https://user-images.githubusercontent.com/92612567/145524936-9bcc8f90-bd1d-4197-8f2e-617884fb108e.png)

**Comment by lovelle-cardoso** [comment]
@LemBurnstein I believe this should be fixed now. Can you try again?

**Comment by LemBurnstein** [comment]
This is fixed!
